###
POST http://127.0.0.1:8080/customer
Content-Type: application/json

{
  "firstName": "Mike",
  "lastName": "Ross",
  "phone": "+89500332255",
  "registrationDate": "Oct 15, 2022, 1:40:51 PM"
}

###
PUT http://127.0.0.1:8080/customer/4
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Snow",
  "phone": "89500442211",
  "registrationDate": "Oct 10, 2022, 6:35:51 PM"
}

###
GET http://127.0.0.1:8080/customer
Content-Type: : application/json

###
GET http://127.0.0.1:8080/customer/4
Accept: application/json

###
DELETE http://127.0.0.1:8080/customer/4


###
GET http://127.0.0.1:8080/order
Content-Type: application/json

###
GET http://127.0.0.1:8080/order/1
Content-Type: application/json

###
GET http://127.0.0.1:8080/order/1/total
Content-Type: application/json


###
GET http://127.0.0.1:8080/category
Content-Type: : application/json

###
GET http://127.0.0.1:8080/category/1
Content-Type: : application/json

###
POST http://127.0.0.1:8080/category
Content-Type: application/json

{
  "name": "Alcohol"
}

###
PUT http://127.0.0.1:8080/category/16
Content-Type: application/json

{
  "name": "Pasta"
}

###
DELETE http://127.0.0.1:8080/category/3
Content-Type: application/json


###
GET http://127.0.0.1:8080/dish
Content-Type: : application/json

###
GET http://127.0.0.1:8080/dish/8
Content-Type: : application/json

###
POST http://127.0.0.1:8080/dish
Content-Type: application/json

{
  "item": "Burger",
  "categoryId": 17,
  "amount": 200,
  "price": 19.90,
  "weight": 50,
  "calories": 67,
  "image": null,
  "description": ""
}

###
PUT http://127.0.0.1:8080/dish/1
Content-Type: application/json

{
  "item": "Cheese",
  "categoryId": 14,
  "amount": 1000,
  "price": 20,
  "weight": null,
  "calories": null,
  "image": "",
  "description": ""
}

###
DELETE http://127.0.0.1:8080/dish/3
Content-Type: application/json